# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('preferred_name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ('preferred_name',),
            },
        ),
    ]
